version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongoDB:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$db_user
      - MONGO_INITDB_ROOT_PASSWORD=$db_pass
  api:
    depends_on:
      - mongo
      - redis
    build: ./server
    restart: unless-stopped
    volumes:
      - nodeVolume:/server
    ports:
      - '5000:5000'
    environment:
      secret_key: $secret_key
      db_url: $db_url
      redis_url: $redis_url
      redis_port: $redis_port
  web:
    depends_on:
      - api
    build:
      context: ./client
      args:
        - REACT_APP_API=$url_domen
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
volumes:
  mongoDB:
  redis:
  nodeVolume:




