version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '7017:27017'
    volumes:
      - mongoDB:/data/db
  api:
    depends_on:
      - mongo
      - redis
    build: ./server
    restart: unless-stopped
    volumes:
      - nodeVolume:/server
    ports:
      - '5000:5000'
    environment:
      secret_key: $secret_key
      db_url: $db_url
      redis_url: $redis_url
      redis_port: $redis_port

volumes:
  mongoDB:
  redis:
  nodeVolume:




