version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: study_platform
    volumes:
      - mongoDB:/data/db
  api:
    depends_on:
      - mongo
      - redis
    build: ./server
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      secret_key: very_secret_key
      db_url: mongodb://mongo:27017/study_platform
      redis_url: redis
      redis_port: 6379
  web:
    depends_on:
      - api
    build:
      context: ./client
      args:
        - REACT_APP_API=http://127.0.0.1:5000
    restart: unless-stopped
    ports:
      - '8888:80'
volumes:
  mongoDB:
  redis:




